#!/bin/bash
#
# Copyright (C) 2016, David Dittrich <dave.dittrich@gmail.com>. All rights reserved.
# (See license at bottom of this file.)

PWNWIKI_NAME="${PWNWIKI_NAME:-pwnwiki}"
PWNWIKI_IP="${PWNWIKI_IP:-127.0.0.1}"
PWNWIKI_PORT="${PWNWIKI_PORT:-1337}"
PWNWIKI_URL="http://${PWNWIKI_IP}:${PWNWIKI_PORT}/"
OS="$(uname -s)"

if [ $OS == "Darwin" -a $PWNWIKI_IP="127.0.0.1" ]; then
	# This might be a bug in Docker for Mac? Not sure.
	PWNWIKI_IP="0.0.0.0"
	PWNWIKI_URL="http://${PWNWIKI_IP}:${PWNWIKI_PORT}/"
fi

# (Re)build pwnwiki container.
docker build --build-arg AUTHOR=$USER -t ${PWNWIKI_NAME} ./
if [ $? -eq 0 ]; then
	echo '[+] pwnwiki container (re)built'
else
	echo '[-] failed to build pwnwiki container'
	exit $?
fi

# Check to see if pwnwiki containter is already running.
pwnwiki_is_running=$(docker ps | grep -q "${PWNWIKI_NAME}";  echo $?)

if [ $pwnwiki_is_running -eq 0 ]; then
	# Kill and remove container.
	docker kill ${PWNWIKI_NAME} 2>&1 >/dev/null || true
	docker rm ${PWNWIKI_NAME} 2>&1 >/dev/null || true
fi

# Run container.
pwnwiki_id=$(docker run -d -p ${PWNWIKI_PORT}:80 --name ${PWNWIKI_NAME} pwnwiki)
if [ $? -eq 0 ]; then
	echo "[+] Started ${PWNWIKI_NAME} container listening on ${PWNWIKI_IP}${PWNWIKI_PORT}"
else
	echo "[-] Failed to start ${PWNWIKI_NAME} container"
	exit $?
fi

# Connect browser (or explain how).
case "$OS" in
	Darwin) open ${PWNWIKI_URL} ;;
	Linux)
		if [ ! -z "$(which gnome-open)" ]; then
			gnome-open ${PWNWIKI_URL};
		elif [ ! -z "$(which x-www-browser)" ]; then
			x-www-browser ${PWNWIKI_URL};
		else
			echo "Connect your browser to ${PWNWIKI_URL}";
		fi ;;
	     *) echo "Connect your browser to ${PWNWIKI_URL}" ;;
esac
exit $?


# Copyright (C) 2016, David Dittrich <dave.dittrich@gmail.com>. All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:
# 
# 1. Redistributions of source code must retain the above copyright notice, this
# list of conditions and the following disclaimer.
# 
# 2. Redistributions in binary form must reproduce the above copyright notice,
# this list of conditions and the following disclaimer in the documentation
# and/or other materials provided with the distribution.
# 
# 3. Neither the name of the copyright holder nor the names of its contributors
# may be used to endorse or promote products derived from this software without
# specific prior written permission.
# 
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
# ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
# WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
# DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
# FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
# DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
# SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
# CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
# OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
# OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
